import Head from "next/head";

import Form1 from "../components/patient-input/Form1";
import HouseholdForm from "components/patient-input/HouseholdForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Neem New Patient</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-slate-800 w-[800px] mx-auto">
        <h1 className="h-20 m-y-auto flex items-center text-2xl font-medium tracking-tight">
          Patient insurance
        </h1>
        <hr className="h-[2px] bg-gray-100 border-0 dark:bg-gray-700 mb-6" />
        <Form1 />
        <HouseholdForm />
      </main>
    </>
  );
}
